### ISSUE TITLE
Client has incorrect knowledge of server state when long-running build process is interrupted

### ISSUE THREAD

**Issue by zackverham** [rstudio/rsconnect-python#467]
I ran into this when I was trying to rebuild content on dogfood after migrating from ubuntu18 to ubuntu22. 

I followed our cache rebuild workflow listed here: https://docs.posit.co/connect/admin/server-management/runtime-caches/#step-2-rebuild-content

After collecting the content that needed to be rebuilt, I filtered down to approximately the last year of deployments. This produced a list of 923 guids which would be used in the rebuild step. 

I kicked off the rebuild on my local machine (following our docs) and let it run overnight. When I came back, I was seeing periodic connectivity errors being produced in stdout, like the following: 

```
[ERROR] 2023-08-23T18:09:51-0400 b2311f56-82f1-4e26-aee5-4fc606627d8b,38498 generated an exception: Exception trying to connect to https://rsc.radixu.com - [Errno 54] Connection reset by peer

[ERROR] 2023-08-23T20:08:25-0400 4d71e092-06da-4c1d-ac91-756314096272,38420 generated an exception: Received an unexpected response from Posit Connect (calling /__api__/v1/content/4d71e092-06da-4c1d-ac91-756314096272/build): 502 Bad Gateway
```

Assuming my local machine going into hibernation could have been the source of connectivity issues, I stopped the process and figured I could restart it, given that rsconnect-python intializes a local store that is tracking the remaining pending tasks. 

This fails with the following: 

```
➜  Downloads rsconnect content build run --name dogfood
[INFO] 2023-08-24T10:23:54-0400 Initializing ContentBuildStore for https://rsc.radixu.com
Error: There is already a build running on this server: https://rsc.radixu.com
```

Investigating the local store's json blob, I see the following flag:
```
    "rsconnect_build_running": true
```

And looking through the source code (cross-checked with @tdstein), I don't think the client attempts to sync its `rsconnect_build_running` flag at startup - it just looks at the current state of the local store. At this point, it has de-synced from the state of the server and isn't correct. 

This means that I can't continue to run the rebuild off of the current state of the store. It is always going to think that a build is currently running and fail out.

**Comment by zackverham** [comment]
Side-note - rsconnect-python is also placing the local store directory in the current working directory where the client is invoked. This means that the store state is tied to where I ran rsconnect-python, which feels incorrect.

**Comment by dbkegley** [comment]
We've seen another instance of this in the wild where the user can't start a new build because the local state is out-of-sync with the server build. There's no way to reset the local state without manually updating the json file.

https://github.com/rstudio/rsconnect-python/blob/5c8a21e504ccef4dc566ec7a14d317c76e7d2deb/rsconnect/metadata.py#L479-L490

The user can set `rsconnect_build_running` to `false` to get past this error, but we should do a better job in rsconnect-python to prevent this from happening in the first place. 

Normally we trap interrupts on the client and set `rsconnect_build_running = false` here: https://github.com/rstudio/rsconnect-python/blob/5c8a21e504ccef4dc566ec7a14d317c76e7d2deb/rsconnect/actions_content.py#L173-L181

If the process is killed and unable to shut down gracefully (this could also happen when hitting `^C` multiple times) then we may never set `rsconnect_build_running = false` which leaves the user stuck.
